/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HomePage: typeof import('./src/pages/HomePage.vue')['default']
    LoginComponent: typeof import('./src/components/auth/LoginComponent.vue')['default']
  }
}
