/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/shared/Alert.vue')['default']
    AuthenticationPage: typeof import('./src/pages/AuthenticationPage.vue')['default']
    Bar: typeof import('./src/components/dashboard/Bar.vue')['default']
    Drawer: typeof import('./src/components/dashboard/Drawer.vue')['default']
    LoginComponent: typeof import('./src/components/auth/LoginComponent.vue')['default']
    ProfileComponent: typeof import('./src/components/dashboard/profile/ProfileComponent.vue')['default']
    RegisterComponent: typeof import('./src/components/auth/RegisterComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    View: typeof import('./src/components/dashboard/View.vue')['default']
  }
}
